volumes:
  postgres-data:
    external: true
  pg-admin:
    external: true
services:

  api:
    build:
      context: vybs_service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./vybs_service:/app
    environment:
      DATABASE_URL: postgresql://user:password-1@db/postgres-data
      WAIT_HOSTS: db:5432
      SIGNING_KEY: ${SIGNING_KEY}
      PORT: 8000
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
  db:
    build:
      context: ./relational-data
      dockerfile: Dockerfile.dev
    image: postgres:14.5-bullseye
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password-1
      POSTGRES_USER: user
      POSTGRES_DB: postgres-data
    ports:
      - "15432:5432"
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: username@username.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: 1
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
